### ISSUE TITLE
The "generate_masks" is missing

### ISSUE THREAD

**Issue by BaohaoLiao** [varunnair18/FISH#10]
Hi,

a errors happen at https://github.com/varunnair18/FISH/blob/b5bff1e66559f7c865e2f45c1488ae13e193dae2/transformers/examples/text-classification/custom_trainer.py#L108, since there are not a file of generate_masks. Could you check this?

**Comment by BaohaoLiao** [comment]
I just found that in another file. Maybe you can update your code.

**Comment by hxu105** [comment]
@BaohaoLiao Hi, could you show me where you find the generate_masks file? Many thanks!

**Comment by BaohaoLiao** [comment]
Hi @hxu105 , all the functions from generate_mask (create_mask_random, create_mask_gradient, create_mask_bias) are at this [file](https://github.com/varunnair18/FISH/blob/main/transformers/examples/text-classification/run_glue_sparse_update.py)
