### ISSUE TITLE
Cannot import name 'MultiSameFisherMask'

### ISSUE THREAD

**Issue by scaldas** [varunnair18/FISH#4]
When trying to run 
`bash cifar10-fast/scripts/distributed_training_fish.sh 256 0.005 50 2 0.4 2
`
I get the error 
`ImportError: cannot import name 'MultiSameFisherMask' from 'fisher' (/Users/sebastian/Code/FisherInformation/FISH/cifar10-fast/fisher.py)
`
I believe the class MultiSameFisherMask doesn't exist in fisher.py, yet it is being imported here: https://github.com/varunnair18/FISH/blob/bfcdad8dacadffceea6ee343e7c561988b839c7b/cifar10-fast/asgd_dawn.py#L6.

**Comment by ylsung** [comment]
Thanks for catching this issue. I added back the missing files in the latest PR. Please try again. Thank you.

**Comment by ylsung** [comment]
Closed due to inactivity.
