### ISSUE TITLE
where is the fisher mask calculation for nlp experiments

### ISSUE THREAD

**Issue by Tsingularity** [varunnair18/FISH#6]
Hi, thanks for the great work!

I found the fisher mask calculation for cifar experiments [here](https://github.com/varunnair18/FISH/blob/b5bff1e66559f7c865e2f45c1488ae13e193dae2/cifar10-fast/fisher.py), but I cannot find the counterpart code for nlp experiments. Could u please share a link to it? Thanks!

**Comment by ylsung** [comment]
We put the codes [here](https://github.com/varunnair18/FISH/blob/b5bff1e66559f7c865e2f45c1488ae13e193dae2/transformers/examples/text-classification/run_glue_sparse_update.py#L155-L242).

**Comment by Tsingularity** [comment]
thanks!
