### ISSUE TITLE
Transformers

### ISSUE THREAD

**Issue by vdeepak13** [varunnair18/FISH#8]
Thanks for making the code available, I see that you have added a fork of transformers, and I am assuming that you have done so since you have made some changes to the internals, could you please point me to those changes if possible?

**Comment by varunnair18** [comment]
We base our training scripts for our method and each of the comparative baselines off of run_glue.py, which is found in `FISH/transformers/examples/text-classification/`. You can find these modified files also in the same folder, and the scripts that call them in `FISH/transformers/examples/text-classification/scripts`.

**Comment by vdeepak13** [comment]
Thanks @varunnair18
